CREATE DATABASE IF NOT EXISTS TODO_LIST;

USE todo_list;

CREATE TABLE IF NOT EXISTS tasks{
    id INT AUTO_INCREMENT PRIMARY KEY,
    title  VARCHAR(255) NOT NULL,
    completed BOOLEAN DEFAULT false
};